workspace = { members = ["src/lib"] }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "fast-blur"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "fast-blur"
path = "src/main.rs"

[dependencies]
half = "2.4.1"
image = "0.25.1"
libblur = {path = "src/lib"}
num-traits = "0.2.19"
rayon = "1.10.0"
yuvutils-rs = {path = "../yuvutils-rs"}
